/*Запросы для добавления производителей*/
INSERT INTO producers(name) VALUES('Samsung');
INSERT INTO producers(name) VALUES('Lenovo');
INSERT INTO producers(name) VALUES('Bosch');
INSERT INTO producers(name) VALUES('Siemens');
INSERT INTO producers(name) VALUES('Gorenje');
INSERT INTO producers(name) VALUES('Asus');
INSERT INTO producers(name) VALUES('LG');
INSERT INTO producers(name) VALUES('Philips');
INSERT INTO producers(name) VALUES('Saturn');
INSERT INTO producers(name) VALUES('Panasonic');
INSERT INTO producers(name) VALUES('GoldStar');
